### ISSUE TITLE
Why is the type file after I run dev called plugin<any>

### ISSUE THREAD

**Issue by proc07** [unplugin/unplugin-starter#27] opened 2024-04-12 08:33 UTC
I just created, just added some hooks

```js
// dist/vite.d.ts
import * as vite from 'vite';
import { Options } from './types.js';

declare const _default: (options?: Options | undefined) => vite.Plugin<any> | vite.Plugin<any>[];

export { _default as default };

```
```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["es2022"],
    "baseUrl": ".",
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "types": ["node"],
    "strict": true,
    "noUnusedLocals": true,
    "declaration": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["src"]
}
```

**Comment by antfu** [comment] 2024-04-12 09:07
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-12 09:07 UTC
